class CreateStrategies < ActiveRecord::Migration[6.0]
  def change
    create_table :strategies do |t|
      t.string :web_scraper_order
      t.string :web_scraper_start_url
      t.string :ticker
      t.string :weight
      t.string :return
      t.string :return_dollars
      t.string :rank
      t.string :shares
      t.string :avg_share_cost
      t.string :current_price
      t.string :value
      t.string :days_held
      t.string :sector
      t.string :return_link
      t.string :return_link_href
      t.string :fundamental_link
      t.string :fundamental_link_href
      t.string :one_day
      t.string :last_close
      t.string :change
      t.string :weight_return
      t.string :one_week
      t.string :four_weeks
      t.string :eight_weeks
      t.string :thirteen_weeks
      t.string :return_fundamental
      t.string :market_cap
      t.string :yield
      t.string :p_e
      t.string :peg
      t.string :roe_ttm
      t.string :roi_ttm
      t.float :tot_debt_to_eq_ratio
      t.string :pr2cfl_per_shr_ttm
      t.string :historical_link
      t.string :historical_link_href
      t.string :cost
      t.string :open_date
      t.integer :number_of_days
      t.string :pct_historical
      t.string :summary_link
      t.string :summary_link_href
      t.string :info_name
      t.string :info_value
      t.string :stats_name
      t.string :stats_value
      t.string :statistics_link
      t.string :statistics_link_href
      t.string :return_pct
      t.string :total
      t.string :model
      t.string :snp_500_spy
      t.string :twenty_twenty_01
      t.string :twenty_twenty_02
      t.string :twenty_twenty_03
      t.string :twenty_twenty_04
      t.string :twenty_twenty_05
      t.string :twenty_twenty_06
      t.string :twenty_twenty_07
      t.string :twenty_twenty_08
      t.string :twenty_twenty_09
      t.string :twenty_twenty_10
      t.string :twenty_twenty_11
      t.string :twenty_twenty_12
      t.string :charts_link
      t.string :charts_link_href
      t.string :trading_statistics_link
      t.string :trading_statistics_link_href
      t.string :trading_values
      t.string :trading_summary_names
      t.string :trading_names
      t.string :realized_all
      t.string :realized_winners
      t.string :realized_losers
      t.string :unrealized_all
      t.string :unrealized_winners
      t.string :unrealized_losers
      t.string :risk_measurements_stats_link
      t.string :risk_measurements_stats_link_href
      t.string :risk_name
      t.string :model_risk
      t.string :snp_500_spy_risk
      t.string :strategy_name

      t.timestamps
    end
  end
end
